# Generated by Django 5.1.4 on 2026-07-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='site',
            name='greeting',
            field=models.CharField(default='Hi! How can we help?', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='position',
            field=models.CharField(choices=[('bottom-right', 'Bottom right'), ('bottom-left', 'Bottom left')], default='bottom-right', max_length=16),
        ),
    ]
