# Generated by Django 5.1.4 on 2026-07-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_site_color_site_greeting_site_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ai_context',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ai_tone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
