# Generated by Django 5.1.4 on 2026-07-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_cannedresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='page_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='site',
            name='pre_chat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
