# Generated by Django 5.1.4 on 2026-07-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_page_url_site_pre_chat_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
