# Generated by Django 5.1.4 on 2026-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='transcript_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
