# Generated by Django 5.1.4 on 2026-07-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_site_transcript_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='feedback_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
